#!/bin/sh
#increase keyboard brightness by 1 on asus G46VW
#NOTE : you have to load asus-nb-wmi on boot
curr_bright=$(cat /sys/class/leds/asus\:\:kbd_backlight/brightness)
max_bright=$(cat /sys/class/leds/asus\:\:kbd_backlight/max_brightness)
new_bright=$(($curr_bright+1))
if (($new_bright <= $max_bright))
then echo "$new_bright">/sys/class/leds/asus\:\:kbd_backlight/brightness
fi